spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.181.240:3306/weibo?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root : info
    com.lrm: info
  file : log/blog-dev.log

server:
  port: 8090



